export const jsonFields = [
  'siteDetails',
  'siteQuestions',
  'photos',
  'streams',
  'meterDetails',
  'kioskDetails',
  'ecvDetails',
  'movDetails',
  'regulatorDetails',
  'standards',
  'meterDetailsTwo',
  'additionalMaterials',
  'dataLoggerDetails',
  'dataLoggerDetailsTwo',
  'maintenanceQuestions',
  'correctorDetails',
  'correctorDetailsTwo',
  'chatterBoxDetails',
];

// keeping the mapping for backward compatibility with the old records
export const fieldMapping = {
  jobID: 'id',
  jobType: 'jobType',
  jobStatus: 'jobStatus',
  startDate: 'startDate',
  endDate: 'endDate',
  rebook: 'rebook',
  siteDetails: 'siteDetails',
  siteQuestions: 'siteQuestions',
  photos: 'photos',
  streams: 'streams',
  meterDetails: 'meterDetails',
  kioskDetails: 'kioskDetails',
  ecvDetails: 'ecvDetails',
  movDetails: 'movDetails',
  regulatorDetails: 'regulatorDetails',
  standards: 'standards',
  meterDetailsTwo: 'meterDetailsTwo',
  additionalMaterials: 'additionalMaterials',
  dataLoggerDetails: 'dataloggerDetails',
  dataLoggerDetailsTwo: 'dataLoggerDetailsTwo',
  maintenanceQuestions: 'maintenanceQuestions',
  correctorDetails: 'correctorDetails',
  correctorDetailsTwo: 'correctorDetailsTwo',
  chatterBoxDetails: 'chatterboxDetails',
};
